language: objective-c
osx_image: xcode11.2
rvm:
- 2.2
before_install:
- chmod a+x ./Travis/install.sh
- chmod a+x ./Travis/build.sh
install:
- ./Travis/install.sh
script:
- ./Travis/build.sh
- ./Travis/test.sh
